# Generated by Django 5.2.1 on 2025-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sports',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
